"use strict";

const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const repoRoot = path.resolve(__dirname, "..");
const sourcePath = path.join(repoRoot, "backups", "casc2.js");
const outputPath = path.join(repoRoot, "js", "fragsheet", "cascade2_save_battle_log_data.js");

function loadCascade2Data() {
    const context = {};
    vm.createContext(context);
    vm.runInContext(fs.readFileSync(sourcePath, "utf8"), context, {
        filename: sourcePath,
        timeout: 30000,
    });

    const data = context.backup_data;
    if (!data || typeof data !== "object"
        || !data.formatted_sets || typeof data.formatted_sets !== "object"
        || !data.order || typeof data.order !== "object") {
        throw new Error("backups/casc2.js does not contain formatted_sets and order data");
    }
    return data;
}

function isHeldItem(item) {
    const normalized = String(item || "").trim().toLowerCase();
    return !!normalized && normalized !== "-" && normalized !== "none";
}

function trainerNameFromSetName(setName) {
    return String(setName || "").replace(/^Lvl\s+-?\d+\s+/i, "");
}

function buildSnapshot(data) {
    const trainerMap = new Map();

    Object.entries(data.formatted_sets).forEach(([speciesName, speciesSets]) => {
        if (!speciesSets || typeof speciesSets !== "object") return;
        Object.entries(speciesSets).forEach(([setName, setData]) => {
            if (!setData || typeof setData !== "object") return;
            const trainerId = Number(setData.tr_id);
            const subIndex = Number(setData.sub_index);
            if (!Number.isInteger(trainerId) || trainerId <= 0
                || !Number.isInteger(subIndex) || subIndex < 0 || subIndex >= 6) {
                return;
            }

            if (!trainerMap.has(trainerId)) {
                trainerMap.set(trainerId, {
                    name: "",
                    level: 10,
                    hasHeldItem: false,
                    species: [],
                });
            }
            const trainer = trainerMap.get(trainerId);
            if (!trainer.species[subIndex]) {
                trainer.species[subIndex] = speciesName;
            }
            if (subIndex === 0) {
                // Match customLeads: later duplicate lead entries replace earlier metadata.
                trainer.name = trainerNameFromSetName(setName);
                trainer.level = Number.isFinite(Number(setData.level)) ? Number(setData.level) : 10;
                trainer.hasHeldItem = isHeldItem(setData.item);
            }
        });
    });

    const trainers = {};
    Array.from(trainerMap.keys()).sort((a, b) => a - b).forEach((trainerId) => {
        trainers[String(trainerId)] = trainerMap.get(trainerId);
    });

    const order = {};
    Object.keys(data.order).map(Number).filter(Number.isInteger).sort((a, b) => a - b)
        .forEach((trainerId) => {
            const node = data.order[String(trainerId)] || data.order[trainerId];
            order[String(trainerId)] = {
                id: Number(node.id),
                next: node.next == null ? null : Number(node.next),
                prev: node.prev == null ? null : Number(node.prev),
            };
        });

    return {
        source: "backups/casc2.js",
        order,
        trainers,
    };
}

function serialize(snapshot) {
    const json = JSON.stringify(snapshot, null, 2);
    return `// Generated by scripts/generate_cascade2_battle_log_data.js. Do not edit manually.\n`
        + `(function (root, factory) {\n`
        + `    const data = factory();\n`
        + `    if (typeof module === "object" && module.exports) module.exports = data;\n`
        + `    if (root) root.Cascade2SaveBattleLogData = data;\n`
        + `})(typeof globalThis !== "undefined" ? globalThis : this, function () {\n`
        + `    "use strict";\n`
        + `    return ${json};\n`
        + `});\n`;
}

const snapshot = buildSnapshot(loadCascade2Data());
fs.writeFileSync(outputPath, serialize(snapshot));
console.log(`Wrote ${outputPath} (${Object.keys(snapshot.trainers).length} trainers, ${Object.keys(snapshot.order).length} order nodes)`);
